[package]
name = "gtk-markdown-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.10"
gio = "0.21"
glib = "0.21"
sourceview5 = "0.10"
pulldown-cmark = "0.13"

[dependencies.adw]
package = "libadwaita"
version = "0.8"
features = ["v1_5"]
